name: utilities
description: Flutter utilities.
version: 0.12.4
repository: "https://github.com/helpisdev/utilities.git"
homepage: "https://utilities.helpis.dev"
documentation: "https://utilities.helpis.dev/docs"
publish_to: none

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.16.5 <4.0.0"

dependencies:
  autoequal: ^0.7.1
  breakpoints_utilities:
    path: packages/resizable_text/packages/breakpoints_utilities
  collection: ^1.18.0
  context_menu:
    path: packages/context_menu
  copy_with_extension: ^5.0.4
  crypto: ^3.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  intl: ^0.19.0
  json_annotation: ^4.8.1
  meta: ^1.11.0
  path: ^1.9.0
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  resizable_text:
    path: packages/resizable_text
  riverpod: ^2.4.9
  screen_size_provider:
    path: packages/resizable_text/packages/screen_size_provider
  shimmer: ^3.0.0
  universal_io: ^2.2.2

dev_dependencies:
  autoequal_gen: ^0.7.1
  build_runner: ^2.4.7
  copy_with_extension_gen: ^5.0.4
  json_serializable: ^6.7.1
  melos: ^3.3.0

dependency_overrides:
  file: ^7.0.0
  intl: ^0.19.0
  material_color_utilities: ^0.8.0
  meta: ^1.11.0
  path: ^1.9.0
  process: ^5.0.1
  pub_updater: ^0.4.0
  web: ^0.4.0
