name: utilities
description: Flutter utilities.
version: 0.9.0
repository: "https://github.com/helpisdev/utilities.git"
homepage: "https://utilities.helpis.dev"
documentation: "https://utilities.helpis.dev/docs"
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  accessibility_tools: ^1.0.0
  adaptive_scaffold:
    git:
      url: https://github.com/helpisdev/adaptive_scaffold.git
      ref: main
  app_links: ^3.4.3
  autoequal: ^0.5.1
  collection: ^1.17.2
  context_menu:
    git:
      url: https://github.com/helpisdev/context_menu.git
      ref: main
  crypto: ^3.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_web_plugins:
    sdk: flutter
  go_router: ^9.0.3
  intl: ^0.18.1
  melos: ^3.0.1
  meta: ^1.9.1
  path: ^1.8.3
  path_provider: ^2.0.15
  permission_handler: ^10.4.2
  platform: ^3.1.0
  riverpod: ^2.3.6
  shimmer: ^3.0.0
  universal_io: ^2.2.2

dev_dependencies:
  autoequal_gen: ^0.5.1
  build_runner: ^2.4.6
